name = "Rogue"
author = "sammyette"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0b4f96fff6076c8bad3e1877612ddc6958759d993eac1069388458b9f5aa8d26"

[versions]
fabric = "0.16.10"
minecraft = "1.21.4"

[options]
datapack-folder = "resources/datapack/required"
